blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/mariolim96/nestjs-starter/blob/main/README.md
    about: Check out the project documentation
  - name: 💬 Discussions
    url: https://github.com/mariolim96/nestjs-starter/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/mariolim96/nestjs-starter/security/advisories/new
    about: Report security vulnerabilities privately