name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! 🤝

  - type: textarea
    id: question
    attributes:
      label: ❓ Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 📂 Category
      description: What category does your question fall into?
      options:
        - Setup & Installation
        - Configuration
        - Usage & Features
        - API & Development
        - Docker & Deployment
        - Database & Migrations
        - Testing
        - Security
        - Performance
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 📋 Context
      description: Provide any relevant context or background information.
      placeholder: What are you trying to achieve? What have you tried so far?

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment (if relevant)
      description: Please provide details about your environment if relevant to your question
      placeholder: |
        - OS: [e.g. Windows 11, macOS 13, Ubuntu 22.04]
        - Node.js version: [e.g. 18.17.0]
        - Package manager: [e.g. pnpm 8.6.0]
        - Docker version: [e.g. 24.0.2]
      value: |
        - OS: 
        - Node.js version: 
        - Package manager: 
        - Docker version: 

  - type: textarea
    id: code-example
    attributes:
      label: 💻 Code Example (if relevant)
      description: If your question is about code, please provide a minimal example.
      render: typescript
      placeholder: Paste your code here...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues and discussions before asking this question
          required: true
        - label: I have checked the documentation
          required: true
        - label: This question is related to this specific project
          required: true