name: 🗑️ Cleanup Workflows

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup-workflow-runs:
    name: 🗑️ Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    
    steps:
      - name: 🗑️ Delete old workflow runs
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Get all workflows
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo
            });
            
            let deletedCount = 0;
            const thirtyDaysAgo = new Date();
            thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
            
            // For each workflow, delete runs older than 30 days
            for (const workflow of workflows.data.workflows) {
              const runs = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflow.id,
                status: 'completed',
                per_page: 100
              });
              
              for (const run of runs.data.workflow_runs) {
                const runDate = new Date(run.created_at);
                if (runDate < thirtyDaysAgo) {
                  try {
                    await github.rest.actions.deleteWorkflowRun({
                      owner,
                      repo,
                      run_id: run.id
                    });
                    deletedCount++;
                    console.log(`Deleted run ${run.id} from ${runDate}`);
                  } catch (error) {
                    console.log(`Failed to delete run ${run.id}: ${error.message}`);
                  }
                }
              }
            }
            
            console.log(`Total workflow runs deleted: ${deletedCount}`);
            return deletedCount;

      - name: 📊 Cleanup summary
        run: |
          echo "## 🗑️ Workflow Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Retention:** 30 days" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ✅ Cleanup completed" >> $GITHUB_STEP_SUMMARY